version: '3.9'

services:
  app:
    image: dong3058/sweepmap:latest # 사용할 이미지 이름
    build:
      context: . # Dockerfile이 위치한 디렉토리
      dockerfile: Dockerfile # 빌드에 사용할 Dockerfile
    ports:
      - "8080:8080" # 호스트와 컨테이너의 포트 매핑
    enviroment:
      KOREA_DATA_PORTAL: ${KOREA_DATA_PORTAL}
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}
      DATA_BASE_URL: ${DATA_BASE_URL}
      DATA_BASE_USERNAME: ${DATA_BASE_USERNAME}
      DATA_BASE_PASSWORD: ${DATA_BASE_PASSWORD}
      REDIS_PASSWORD: ${REDIS_PASSOWRD}}
      ODSAY: ${ODSAY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      RABBIT_PASSWORD: ${RABBIT_PASSWORD}
      
    networks:
      - sweepMap-network
    restart: always
    
  redis:  
    image: redis:7-alpine
    command: redis-server --requirepass test
    ports:
      - "6379:6379"
    networks:
      - sweepMap-network
    restart: always
    
networks:
  sweepMap-network:
    external: true
