spring:
  application:
    name: project
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: false

discord:
  mq-url:
